name: secret mounting

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to GCF
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ⬇️ Check out code
        uses: actions/checkout@v3

      - name: 🗝️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: full project id with version
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: id-with-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: /secrets/secrets.json=projects/${{secrets.PROJECT_ID}}/secrets/secrets/versions/1

      - name: full project id with implied latest
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: id-with-implied-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: /secrets/secrets.json=projects/${{secrets.PROJECT_ID}}/secrets/secrets

      - name: full project number with version
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: number-with-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: /secrets/secrets.json=projects/${{secrets.PROJECT_NUMBER}}/secrets/secrets/versions/1

      - name: full project number with implied latest
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: number-with-implied-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: /secrets/secrets.json=projects/${{secrets.PROJECT_NUMBER}}/secrets/secrets

      - name: partial project id with implied latest
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: partial-project-with-implied-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: /secrets/secrets.json=${{secrets.PROJECT_ID}}/secrets/secrets

      - name: partial project number with implied latest
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: partial-number-with-implied-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: /secrets/secrets.json=${{secrets.PROJECT_NUMBER}}/secrets/secrets
